### ISSUE TITLE
UFW is disabled or you are not root user

### ISSUE THREAD

**Issue by aq2kx** [chaifeng/ufw-docker#23]
Hi, in a test server with Ubuntu 18.04 I've tried to use your tool and I've got this error:

root@stage:/opt/ufw-docker/ufw-docker# ufw-docker install
ERROR: UFW is disabled or you are not root user.

Ufw is enabled with these rules:
Anywhere                   ALLOW       79.8.127.0
Anywhere                   ALLOW       192.168.169.0/24 

Could you help me?
Thnx

**Comment by chaifeng** [comment]
Could you show me the result of the following commands?

    ufw version
    ufw status; echo $?
    cat /etc/issue
    uname -a



On December 2, 2019 at 17:05:24, aq2kx (notifications@github.com) wrote:

Hi, in a test server with Ubuntu 18.04 I've tried to use your tool and I've
got this error:

root@stage:/opt/ufw-docker/ufw-docker# ufw-docker install
ERROR: UFW is disabled or you are not root user.

Ufw is enabled with these rules:
Anywhere ALLOW 79.8.127.0
Anywhere ALLOW 192.168.169.0/24

Could you help me?
Thnx

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/chaifeng/ufw-docker/issues/23?email_source=notifications&email_token=AAAZ247QWFBUU2UKI7DUWYLQWTFVHA5CNFSM4JTSPPKKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4H5GG2VA>,
or unsubscribe

**Comment by aq2kx** [comment]
**ufw version**
ufw 0.36

**ufw status; echo $?**
State: enabled

To                          Action      FROM
-                          ------      --
Anywhere                   ALLOW       79.8.xx.xx
Anywhere                   ALLOW       192.168.169.0/24
443                        ALLOW       79.8.xx.xx

**cat /etc/issue**
Ubuntu 18.04.3 LTS \n \l

**uname -a**
79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by chaifeng** [comment]
The first line of your `ufw status` is weird.

It should be: `Status: active`, yours is `State: enabled`.

I also checked the ufw source code, it's `Status: active`, https://git.launchpad.net/ufw/tree/locales/po/en_AU.po?h=ubuntu/master

Could you show the result:

      type -a ufw

**Comment by aq2kx** [comment]
You're right, it's enabled. I used a wrong tranlation. Sorry
